### ISSUE TITLE
[feat] 회의 생성하기 서버 연결

### ISSUE THREAD

**Issue by abi-hong** [Hello-Plum/Plum-Client#6]
## ✏️ Description
- 회의 생성하기 서버 연결 하겠습니다.

## 📋 TODO
- [x] 서버연결(using Axios) 
- [x] CORS 에러 발생
- [ ] React-Query 사용하기 -> 리팩토링할 때, 적용해보자~!
