### ISSUE TITLE
[refactor] 회의 생성하기 리팩토링

### ISSUE THREAD

**Issue by abi-hong** [Hello-Plum/Plum-Client#7]
## ✏️ Description
- 회의 생성하기 리팩토링하겠습니다.

## 📋 TODO
컴포넌트
- [x] atom 컴포넌트 분리(Input, StringButton)

예외 처리
- [x] 각 필드마다 입력 시 버튼 활성화
- [x] 각 필드 예외 처리 → 회의 이름(15자 이내) / 기간(7일 이내) / 장소(클릭 시 활성화, 장소 디테일 필드 추가)

디자인
- [x] BodyComponent CSS 수정
